name: Run Tests

on: [push]

jobs:
  cypress-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v2
      - name: CI Setup
        run: |
          npm ci
          npx cypress verify
          npx cypress info
      - name: Execute Cypress tests
        run: node cypress/testRunner.js run --id $GITHUB_RUN_ID --branch $GITHUB_REF --commit "${{ github.event.head_commit.message }}"

      - uses: actions/upload-artifact@v2
        with:
          name: tests-report
          path: cypress/tmp/reports
